/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;


public class StringUtils {

	public boolean isPositiveNumber(String str) throws NumberFormatException {

		int number = Integer.parseInt(str);
		if (number > 0) {
			return true;
		}
		return false;

	}

}