/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;


public class StringUtils {

	public boolean isPositiveNumber(String str) throws NumberFormatException {

		int number = Integer.parseInt(str);
		if (number > 0) {
			return true;
		}
		return false;

	}

public boolean isAllPositiveNumbers(String... str) throws NumberFormatException {

		for(int i = 0; i < str.length; i++) {
			if (i <= 0) {
				return false;
			}	
		}
		return true;
	}

}