/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package utils;


public class Utils {

public static boolean isAllPositiveNumbers(String... str) throws NumberFormatException {

		return StringUtils.isAllPositiveNumbers(str);
	}

}