/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package utils;


import utils.StringUtils;


public class Utils {

public static boolean isAllPositiveNumbers(String... str) throws NumberFormatException {
		return StringUtils.isAllPositiveNumbers(str);
	

	}

}