/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;


class StringUtilsTest {
    
@Test
	public void testIsPositiveNumber() {
		assertTrue(StringUtils.isPositiveNumber("5"));
		assertFalse(StringUtils.isPositiveNumber("0"));
		assertFalse(StringUtils.isPositiveNumber("-3"));
	} 
}

}
